### ISSUE TITLE
[BUG] Non-existent valueset expansion returns 200

### ISSUE THREAD

**Issue by kzotoff** [Aidbox/Issues#465] opened 2022-01-17 19:45 UTC
First, get any name which is not id of any ValueSet, for example, `something-that-does-not-exist`

Now `GET /ValueSet/something-that-does-not-exist/$expand`. Result will contain error message but HTTP result is 200.
But `GET /ValueSet/something-that-does-not-exist` returns 404.

It will be much more consistent if both requests will return 404.

**Comment by ddegr** [comment] 2022-01-21 12:40
Fixed on `Aidbox:edge`

**Comment by Nesmeshnoy** [comment] 2022-01-21 17:26
@kzotoff can you try it and let us know if it works as expected?

**Comment by kzotoff** [comment] 2022-01-21 17:37
tested at devbox:edge v:2201.6bf1d78e

`GET /ValueSet/crazy/$expand`

Status: 404
message: ValueSet/crazy not found

**Comment by ruscoder** [comment] 2022-03-03 19:19
The latest changes have broken POST ValueSet/$expand operation (example from doc https://docs.aidbox.app/terminology/valueset/value-set-expansion#valueset)

Example:
```
post /ValueSet/$expand

resourceType: Parameters
parameter:
- name: valueSet
  resource:
    resourceType: ValueSet
    compose:
      include:
        - system: http://snomed.info/sct
          concept:
            - code: '5000'
              display: Concept 5000
            - code: '1000'
              display: Concept 1000
            - code: '9000'
              display: Concept 9000
            - code: '2000'
              display: Concept 2000
            - code: '3000'
              display: Concept 3000
            - code: '11000'
              display: Concept 11000

```

Actual:
```
404

message: ValueSet/ not found
```

This worked on 2112.

**Comment by KGOH** [comment] 2022-03-04 09:20
@ruscoder could not reproduce on :edge. Here's a notebook with our steps
`https://aidbox.app/ExportedNotebook/def035f8-0b4f-42e0-8609-7f450bb1ef36`
You can import it into your Aidbox and check if you have the same behavior

On :latest error can be reproduced. We're going to release new :latest next week

Please confirm that issue is fixed for you on :edge

**Comment by Nesmeshnoy** [comment] 2022-03-09 08:05
Hi @ruscoder, any updates on the issue?

**Comment by ruscoder** [comment] 2022-03-09 10:59
@Nesmeshnoy works for me on edge. Thank you!

**Closed** 2022-03-22 16:28 UTC
Labels: improvement
