### ISSUE TITLE
When using _elements not all properties are being returned

### ISSUE THREAD

**Issue by yosbeleg89** [Aidbox/Issues#413] opened 2021-08-10 14:25 UTC
**Describe the bug**
In the latest Aidbox version, when using _elements, when filtering a Practitioner, other attributes work but when adding `active` it is not in the response.

**Severity**
Even when there is a workaround of not using `_elements` it is critical because on those places where it is being used the response is incorrect, since FHIR says that if no `active` it is considered as active.

**Steps to reproduce the behavior:**
Make an API call like:
```
GET /fhir/Practitioner?_id=976894f5-8c54-4c3d-8c4e-0007663fbf28&_elements=active,id
accept: application/json
```
the response does not contains `active` property on entries.

**Versions:**
 - Aidbox image version
healthsamurai/multibox:stable

**Comment by ddegr** [comment] 2021-08-13 10:50
Could not reproduce on `multibox:stable` and `multibox:edge`

![image](https://user-images.githubusercontent.com/9136211/129346118-29b75522-b539-435a-8cb1-75e0348b8385.png)

**Comment by ddegr** [comment] 2021-08-13 10:50
Could you please give data example and verify if the issue still exists.

**Comment by ddegr** [comment] 2021-08-13 16:11
Fixed on `edge`

**Closed** 2021-08-13 16:12 UTC
Labels: bug
