### ISSUE TITLE
GET Observation and DiagnosticReport by subject patient id filter

### ISSUE THREAD

**Issue by alexpigarev** [Aidbox/Issues#373] opened 2021-03-31 12:08 UTC
GET /Observation?subject=Patient/[Patient_id]
GET /DiagnosticReport?subject=Patient/[Patient_id]

error w6 [60011ms] Request time is longer than timeout - 60 sec SELECT "observation".* FROM "observation" WHERE "observation".resource @> ? LIMIT ? OFFSET ? ["{\"subject\":{\"resourceType\":\"Patient\",\"id\":\"PatientId\"}}" "100" "0"]

resourceType: OperationOutcome
id: 'exception'
text:
  status: generated
  div: "class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')"
issue:
  - severity: fatal
    code: exception
    diagnostics: "class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')"

**Comment by KGOH** [comment] 2021-04-01 09:08
It seems that you have string instead of number somewhere in your database's `observation` and `diagnosticreport` tables. This may happen after using `$load` endpoint

**Comment by KGOH** [comment] 2021-04-01 12:07
Couldn't reproduce the error. Won't fix right now. Your main issue is the timeout because of slow database query

This error arises because of some unexpected error after catching PostgreSQL timeout error

**Closed** 2021-04-13 09:34 UTC
Labels: bug, on-hold
